BaSP-TG-132-superadmin-redux
BaSP-m2022/coco-trackgenix-app pull request #40
Opened 2022-06-14 04:50 UTC by dayanagm96

Implementing Redux on SuperAdmins for:
- Creation of constants.
- Creation of actions.
- Creation of reducers.
- Creation of thunks.

Implementing share components as well.

2022-06-16 04:15 UTC, Lucas-DeLorenzi requested changes

2022-06-16 04:15 UTC, Lucas-DeLorenzi commented on src/Components/SuperAdmins/SuperAdminFormEdit.jsx
> +  const handleInput1 = (e) => {
the same suggestions as in the add form

2022-06-16 04:15 UTC, Lucas-DeLorenzi commented on src/Components/SuperAdmins/SuperAdminFormEdit.jsx
>          <Button
the same suggestions as in the add form, about modal and her buttons and actions

2022-06-16 04:15 UTC, Lucas-DeLorenzi commented on src/Components/redux/modules/superAdmins/thunks.js
> +      const response = await fetch(`https://coco-trackgenix-server.vercel.app/SuperAdmins`, {
depending on the fetch result you could configure the buttons and messages that are displayed in the modals

2022-06-16 04:15 UTC, Lucas-DeLorenzi commented on src/Components/SuperAdmins/SuperAdminForm.jsx
>            <Button
clicking this button if the fields have errors, the screen turns white

2022-06-16 04:15 UTC, Lucas-DeLorenzi commented on src/Components/SuperAdmins/SuperAdminFormEdit.jsx
>        <h2>Form Edit</h2>
in edit function it seems that the server accepts any type of input in the inputs: special characters, empty strings... it never fails

2022-06-16 04:15 UTC, Lucas-DeLorenzi commented on src/Components/redux/modules/superAdmins/thunks.js
> +export const deleteSuperAdmins = (_id) => {
the same suggestion as in add function

2022-06-16 04:15 UTC, Lucas-DeLorenzi commented on src/Components/redux/modules/superAdmins/thunks.js
> +export const editSuperAdmin = (superAdmin, id) => {
the same suggestion as in add function

2022-06-17 21:33 UTC, Lucas-DeLorenzi approved these changes

2022-06-17 21:38 UTC, DeepFreq approved these changes

2022-06-17 21:43 UTC, Juanoauil approved these changes

2022-06-17 23:11 UTC, merged